from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtGui import QIcon


class Ui_Shop_Window(object):
    def shop_window_Ui(self, Shop_Window):
        Shop_Window.setObjectName("Shop_Window")
        Shop_Window.resize(1920, 1080)
        self.label = QtWidgets.QLabel(Shop_Window)
        self.label.setGeometry(QtCore.QRect(0, 0, 1920, 1080))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("db/data/maxresdefault.jpg").scaled(1920, 1080))
        self.label.setObjectName("label")
        self.shop_label = QtWidgets.QLabel(Shop_Window)
        self.shop_label.setGeometry(QtCore.QRect(690, 50, 380, 111))
        font = QtGui.QFont()
        font.setFamily("Minecraft Seven Cyrillic (russi")
        font.setPointSize(55)
        self.shop_label.setFont(font)
        self.shop_label.setStyleSheet("color: rgb(255, 255, 255);")
        self.shop_label.setObjectName("shop_label")
        self.check_balance = QtWidgets.QLineEdit(Shop_Window)
        self.check_balance.setGeometry(QtCore.QRect(1550, 70, 161, 41))
        font = QtGui.QFont()
        font.setFamily("Minecraft Seven Cyrillic (russi")
        font.setPointSize(15)
        self.check_balance.setFont(font)
        self.check_balance.setStyleSheet("background-color: rgb(50, 71, 163);\n"
                                         "color: rgb(255, 255, 255);")
        self.check_balance.setReadOnly(True)
        self.check_balance.setObjectName("check_balance")
        self.balance_label = QtWidgets.QLabel(Shop_Window)
        self.balance_label.setGeometry(QtCore.QRect(1430, 70, 111, 31))
        font = QtGui.QFont()
        font.setFamily("Minecraft Seven Cyrillic (russi")
        font.setPointSize(18)
        self.balance_label.setFont(font)
        self.balance_label.setStyleSheet("color: rgb(255, 255, 255);")
        self.balance_label.setObjectName("balance_label")
        self.player_speed_level_1 = QtWidgets.QPushButton(Shop_Window)
        self.player_speed_level_1.setGeometry(QtCore.QRect(760, 280, 161, 41))
        font = QtGui.QFont()
        font.setFamily("Minecraft Seven Cyrillic (russi")
        font.setPointSize(14)
        self.player_speed_level_1.setFont(font)
        self.player_speed_level_1.setStyleSheet("background-color: rgb(50, 71, 163);\n"
                                                "color: rgb(255, 228, 24);")
        self.player_speed_level_1.setObjectName("pushButton_1")

        self.shoot_rate_level_1 = QtWidgets.QPushButton(Shop_Window)
        self.shoot_rate_level_1.setGeometry(QtCore.QRect(760, 370, 161, 41))
        font = QtGui.QFont()
        font.setFamily("Minecraft Seven Cyrillic (russi")
        font.setPointSize(14)
        self.shoot_rate_level_1.setFont(font)
        self.shoot_rate_level_1.setStyleSheet("background-color: rgb(50, 71, 163);\n"
                                              "color: rgb(255, 228, 24);")
        self.shoot_rate_level_1.setObjectName("pushButton_4")

        self.go_back_button = QtWidgets.QPushButton(Shop_Window)
        self.go_back_button.setGeometry(QtCore.QRect(10, 20, 75, 61))
        font = QtGui.QFont()
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.go_back_button.setFont(font)
        self.go_back_button.setStyleSheet("border-radius : 50; \n"
                                          "color: rgb(255, 255, 255);\n"
                                          "border : 2px solid white\n"
                                          "")
        self.go_back_button.setObjectName("go_back_button")
        self.no_money_label = QtWidgets.QLabel(Shop_Window)
        self.no_money_label.setGeometry(QtCore.QRect(710, 610, 301, 41))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.no_money_label.setFont(font)
        self.no_money_label.setStyleSheet("background-color: rgb(255, 175, 175);\n"
                                          "color: rgb(255, 0, 0);\n"
                                          "\n"
                                          "border-radius : 50; \n"
                                          "border : 3px solid red;")
        self.no_money_label.setObjectName("label_2")
        self.player_speed_boost = QtWidgets.QLabel(Shop_Window)
        self.player_speed_boost.setGeometry(QtCore.QRect(480, 280, 251, 31))
        font = QtGui.QFont()
        font.setFamily("Minecraft Seven Cyrillic (russi")
        font.setPointSize(16)
        self.player_speed_boost.setFont(font)
        self.player_speed_boost.setStyleSheet("color: rgb(255, 255, 255);")
        self.player_speed_boost.setObjectName("player_speed_boost")

        self.level_1 = QtWidgets.QLabel(Shop_Window)
        self.level_1.setGeometry(QtCore.QRect(940, 280, 251, 31))
        font = QtGui.QFont()
        font.setFamily("Minecraft Seven Cyrillic (russi")
        font.setPointSize(16)
        self.level_1.setFont(font)
        self.level_1.setStyleSheet("color: rgb(255, 255, 255);")
        self.level_1.setObjectName("level_1")

        self.level_2 = QtWidgets.QLabel(Shop_Window)
        self.level_2.setGeometry(QtCore.QRect(940, 370, 251, 31))
        font = QtGui.QFont()
        font.setFamily("Minecraft Seven Cyrillic (russi")
        font.setPointSize(16)
        self.level_2.setFont(font)
        self.level_2.setStyleSheet("color: rgb(255, 255, 255);")
        self.level_2.setObjectName("level_2")

        self.level_3 = QtWidgets.QLabel(Shop_Window)
        self.level_3.setGeometry(QtCore.QRect(940, 460, 251, 31))
        font = QtGui.QFont()
        font.setFamily("Minecraft Seven Cyrillic (russi")
        font.setPointSize(16)
        self.level_3.setFont(font)
        self.level_3.setStyleSheet("color: rgb(255, 255, 255);")
        self.level_3.setObjectName("level_3")

        self.shoot_rate_boost = QtWidgets.QLabel(Shop_Window)
        self.shoot_rate_boost.setGeometry(QtCore.QRect(460, 370, 271, 31))
        font = QtGui.QFont()
        font.setFamily("Minecraft Seven Cyrillic (russi")
        font.setPointSize(16)
        self.shoot_rate_boost.setFont(font)
        self.shoot_rate_boost.setStyleSheet("color: rgb(255, 255, 255);")
        self.shoot_rate_boost.setObjectName("shoot_rate_boost")
        self.shoot_speed_boost = QtWidgets.QLabel(Shop_Window)
        self.shoot_speed_boost.setGeometry(QtCore.QRect(520, 460, 201, 31))
        font = QtGui.QFont()
        font.setFamily("Minecraft Seven Cyrillic (russi")
        font.setPointSize(16)
        self.shoot_speed_boost.setFont(font)
        self.shoot_speed_boost.setStyleSheet("color: rgb(255, 255, 255);")
        self.shoot_speed_boost.setObjectName("shoot_speed_boost")
        self.shoot_speed_level_1 = QtWidgets.QPushButton(Shop_Window)
        self.shoot_speed_level_1.setGeometry(QtCore.QRect(760, 460, 161, 41))
        font = QtGui.QFont()
        font.setFamily("Minecraft Seven Cyrillic (russi")
        font.setPointSize(14)
        self.shoot_speed_level_1.setFont(font)
        self.shoot_speed_level_1.setStyleSheet("background-color: rgb(50, 71, 163);\n"
                                               "color: rgb(255, 228, 24);")
        self.shoot_speed_level_1.setObjectName("pushButton_7")

        self.retranslateUi(Shop_Window)
        QtCore.QMetaObject.connectSlotsByName(Shop_Window)

    def retranslateUi(self, Shop_Window):
        _translate = QtCore.QCoreApplication.translate
        Shop_Window.setWindowTitle(_translate("Shop_Window", "Astralix"))
        Shop_Window.setWindowIcon(QIcon('db/data\pngwing.png'))
        self.shop_label.setText(_translate("Shop_Window", "Магазин"))
        self.check_balance.setText(_translate("Shop_Window", " 0"))
        self.balance_label.setText(_translate("Shop_Window", "Баланс:"))

        self.go_back_button.setText(_translate("Shop_Window", "Back"))
        self.no_money_label.setText(_translate("Shop_Window", "Не достаточно средств"))
        self.player_speed_boost.setText(_translate("Shop_Window", "Скорость корабля:"))
        self.shoot_rate_boost.setText(_translate("Shop_Window", "Скорость стрельбы:"))
        self.shoot_speed_boost.setText(_translate("Shop_Window", "Скорость пули:"))

        self.level_1.setText(_translate("Shop_Window", "Уровень 1"))
        self.level_2.setText(_translate("Shop_Window", "Уровень 1"))
        self.level_3.setText(_translate("Shop_Window", "Уровень 1"))

        self.shoot_speed_level_1.setText(_translate("Shop_Window", "2 ss"))
        self.player_speed_level_1.setText(_translate("Shop_Window", "2 pl"))
        self.shoot_rate_level_1.setText(_translate("Shop_Window", "2 sr"))
